setwd("/Users/trung/Documents/Umass_rs/bug_fix_minimization/plots/D4J")
getwd()
#D4J plots
png(filename="INS.png")
hist(diff_merge$INS,main="Distribution of inserted lines",xlab="lines")
dev.off()
png(filename="DEL.png")
hist(diff_merge$DEL,main="Distribution of deleted lines",xlab="lines")
dev.off()
png(filename="MOD.png")
hist(diff_merge$MOD,main="Distribution of modified lines",xlab="lines")
dev.off()
png(filename="Inserted.png")
hist(diff_merge$inserted,main="Distribution of inserted lines",xlab="lines")
dev.off()
png(filename="Deleted.png")
hist(diff_merge$deleted,main="Distribution of deleted lines",xlab="lines")
dev.off()
png(filename="Modified.png")
hist(diff_merge$modified,main="Distribution of modified lines",xlab="lines")
dev.off()
png(filename="INS_DIF.png")
hist(diff_merge$ins_diff,main="Distribution of differences in inserted lines",xlab="lines")
dev.off()
png(filename="DEL_DIF.png")
hist(diff_merge$del_diff,main="Distribution of differences in deleted lines",xlab="lines")
dev.off()
png(filename="MOD_DIF.png")
hist(diff_merge$mod_diff,main="Distribution of differences in modified lines",xlab="lines")
dev.off()
setwd("/Users/trung/Documents/Umass_rs/bug_fix_minimization/plots/testedness")
getwd()
#testedness plots
png(filename="inserted.png")
hist(testedness_dff$inserted,main="Distribution of inserted lines",xlab="lines")
dev.off()
png(filename="deleled.png")
hist(testedness_dff$deleted,main="Distribution of deleted lines",xlab="lines")
dev.off()
png(filename="modified.png")
hist(testedness_dff$modified,main="Distribution of modified lines",xlab="lines")
dev.off()