setwd("/Users/trung/Documents/Umass_rs/bug_fix_minimization/plots/D4J")
getwd()
#D4J plots
png(filename="INS.png")
plot(density(merge_diff$INS),main="Distribution of inserted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="DEL.png")
plot(density(merge_diff$DEL),main="Distribution of deleted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="MOD.png")
plot(density(merge_diff$MOD),main="Distribution of modified lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="Inserted.png")
plot(density(merge_diff$inserted),main="Distribution of inserted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="Deleted.png")
plot(density(merge_diff$deleted),main="Distribution of deleted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="Modified.png")
plot(density(merge_diff$modified),main="Distribution of modified lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="INS_DIF.png")

plot(density((merge_diff$ins_diff)/( ifelse(merge_diff$INS ==0,1,merge_diff$INS))*100),main="Distribution of differences in inserted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="DEL_DIF.png")
plot(density((merge_diff$del_diff)/( ifelse(merge_diff$DEL ==0,1,merge_diff$DEL))*100),main="Distribution of differences in deleted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="MOD_DIF.png")
plot(density((merge_diff$mod_diff )/( ifelse(merge_diff$MOD ==0,1,merge_diff$MOD))*100),main="Distribution of differences in modified lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="File_DIF.png")
hist(((as.numeric(commit_changes_files$nf_diff))/as.numeric(commit_changes_files$nfcm)*100),main="Distribution of differences in number of changed files",xlab="Increase percentage",xaxt='n',xlim=c(0,3000),breaks=seq(0,3000,by=40))
axis(1, at = seq(0, 3000, by = 100))
dev.off()
setwd("/Users/trung/Documents/Umass_rs/bug_fix_minimization/plots/testedness")
getwd()
#testedness plots
#png(filename="inserted.png")
#plot(density(testedness_dff$inserted),main="Distribution of inserted lines",xlab="lines",xaxt='n')
#axis(1, at = seq(-5, 60, by = 3))
#dev.off()
#png(filename="deleled.png")
#plot(density(testedness_dff$deleted),main="Distribution of deleted lines",xlab="lines",xaxt='n')
#axis(1, at = seq(-5, 60, by = 3))
#dev.off()
#png(filename="modified.png")
#plot(density(testedness_dff$modified),main="Distribution of modified lines",xlab="lines",xaxt='n')
#axis(1, at = seq(-5, 60, by = 3))
#dev.off()