setwd("/Users/trung/Documents/Umass_rs/bug_fix_minimization/plots/D4J")
getwd()
#D4J plots
png(filename="INS.png")
plot(density(diff_merge$INS),main="Distribution of inserted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="DEL.png")
plot(density(diff_merge$DEL),main="Distribution of deleted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="MOD.png")
plot(density(diff_merge$MOD),main="Distribution of modified lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="Inserted.png")
plot(density(diff_merge$inserted),main="Distribution of inserted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="Deleted.png")
plot(density(diff_merge$deleted),main="Distribution of deleted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="Modified.png")
plot(density(diff_merge$modified),main="Distribution of modified lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="INS_DIF.png")
plot(density(diff_merge$ins_diff),main="Distribution of differences in inserted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="DEL_DIF.png")
plot(density(diff_merge$del_diff),main="Distribution of differences in deleted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="MOD_DIF.png")
plot(density(diff_merge$mod_diff),main="Distribution of differences in modified lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="File_DIF.png")
hist(as.numeric(commit_changes_files$nf_diff),main="Distribution of differences in number of changed files",xlab="files",xaxt='n',xlim=c(-1,30),breaks=seq(-1,30,by=1))
axis(1, at = seq(0, 30, by = 1))
dev.off()
setwd("/Users/trung/Documents/Umass_rs/bug_fix_minimization/plots/testedness")
getwd()
#testedness plots
png(filename="inserted.png")
plot(density(testedness_dff$inserted),main="Distribution of inserted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="deleled.png")
plot(density(testedness_dff$deleted),main="Distribution of deleted lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()
png(filename="modified.png")
plot(density(testedness_dff$modified),main="Distribution of modified lines",xlab="lines",xaxt='n')
axis(1, at = seq(-5, 60, by = 3))
dev.off()